### ISSUE TITLE
Add to awesome-cakephp

### ISSUE THREAD

**Issue by dereuromark** [wouter0100/cakephp-opauth#1]
Your 2.x plugin is already in there (strike through):
https://github.com/FriendsOfCake/awesome-cakephp/tree/cake3#authentication-and-authorization

Maybe you want to replace it with your new 3.x one (and reorder it alphabetically).

**Comment by wouter0100** [comment]
Thanks, created a pull request.

**Comment by dereuromark** [comment]
You might want to add test coverage + travis support by the way.

**Comment by wouter0100** [comment]
I'll add that soon, yeah.
