### ISSUE TITLE
Error: Unsupported operand types

### ISSUE THREAD

**Issue by aceat64** [wouter0100/cakephp-opauth#2]
After allowing access to my Google account, I receive the following error on the */auth/google/callback* page:

> Error: Unsupported operand types 
> File /var/www/taskr/vendor/cakephp/cakephp/src/Network/Request.php 
> Line: 227

**Comment by aceat64** [comment]
Ok, after realizing that I shouldn't be loading my Strategy as `$config['Opauth']['Config']['Strategy']['Google']` I get this error:

> Error: Unsupported operand types 
> File /var/www/taskr/vendor/wouter0100/cakephp-opauth/src/Controller/OpauthController.php 
> Line: 67

**Comment by wouter0100** [comment]
Could you please test this fix and leave a comment if its working or not?

**Comment by aceat64** [comment]
Now I get:

> Error: Unsupported operand types 
> File /var/www/taskr/vendor/wouter0100/cakephp-opauth/src/Controller/OpauthController.php 
> Line: 63

It looks like Configure::read('Opauth.Config') is returning null. After closer review, I think I was wrong to have `$config['Opauth']['Config']['Strategy']`, because [line 68 of OpauthController.php](https://github.com/wouter0100/cakephp-opauth/blob/cb6a5412a4ab9d329f576ed527b7bb0bcf1bc4c1/src/Controller/OpauthController.php#L68) loads `$config['Opauth']['Strategy']`. I'm submitting a pull request to revert the README and fix my mistake there.

I fiddled around with the bootstrap.php and opauth.php config files of the plugin and it seems that the plugin's opauth.php never gets called. If I add the following to the bottom of the plugin's bootstrap.php, the opauth.php config will get loaded:

> Configure::load('Wouter0100/Opauth.opauth');

Now I get sent off to Google for OAuth. Awesome! Unfortunately, once I get sent back to the app, I get a fatal error:

> Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 68 bytes) in /var/www/taskr/vendor/opauth/opauth/src/Opauth.php on line 112

The error persists, even if I push the `memory_limit` to 2GB, which makes me think we've got an infinite loop going on.

**Comment by sitedyno** [comment]
@aceat64 I also encountered the operand errors but got rid of them by making sure that all the config options the plugin expects are set. This is how my app/config/opauth.php file looks: https://gist.github.com/sitedyno/6811003f801c468fbe00

**Comment by wouter0100** [comment]
The `Config/opauth.php` is a example file, which isn't being used (maybe need to change this to something like `opauth.default.php`?). I've updated the module, now it should check the output of `Configure::read` to ensure it's an array. If it's not (for example null) we'll create an empty array to add the defaults.

If you create a config file in your `config/opauth.php` with for example:
```php
$config = [];
$config['Opauth'] = [];

$config['Opauth']['Config'] = [];

$config['Opauth']['CompleteURL'] = '/users/complete';

$config['Opauth']['Strategy'] = [];

$config['Opauth']['Strategy']['Facebook'] = [
    'app_id' => null,
    'app_secret' => 'secret'
];
```

It should work. To overwrite our other defaults (callback, path) you have to add this after the `$config['Opauth']['Config'] = [];` line, with the updated values:
```php
$config['Opauth']['Config']['callback'] = 'opauth-callback';
$config['Opauth']['Config']['path'] = '/auth/success';
```

Or do I interpret CakePHP's `Configure` things wrong here?

**Comment by sitedyno** [comment]
:+1:  to opauth.default.php

It might be better to throw an exception if the value returned is not an array, something like
> opauth configuration not loaded (or not found).

This plugin *needs* configuration so writing a default config if the file isn't found isn't really helpful imo and will be more frustrating for implementers since they don't receive `useful` feedback.

Checking for at least one provider and throwing an exception if there isn't one would probably be helpful as well.

**Comment by aceat64** [comment]
Thanks @wouter0100, I won't be able to test this until late Friday. I'll update this issue once I've tested it.

**Comment by aceat64** [comment]
Awesome, the config you gave works. I was able to auth against google.

**Comment by aceat64** [comment]
With further testing I was able to get it working with just the following config:

```php
$config['Opauth']['CompleteURL'] = '/users/complete';

$config['Opauth']['Strategy']['Google'] = [
    'client_id' => '__change_me__',
    'client_secret' => '__change_me__'
];
```

**Comment by aceat64** [comment]
With pull request #5 I think we can call this issue closed.
